services:
  nginx:
    container_name: devimarket-nginx
    build:
      context: ../..
      dockerfile: team7_infrastructure/docker_compose_setup/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ../../frontend/dist/:/usr/share/nginx/html:ro
    networks:
      - devimarket-net
    restart: unless-stopped

  clickhouse:
    container_name: devimarket-clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ../clickhouse_init_scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - devimarket-net
    restart: unless-stopped

volumes:
  clickhouse_data:

networks:
  devimarket-net:
    driver: bridge
